# Generated by Django 6.1.1 on 2026-09-22 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('service', models.CharField(choices=[('residential_move', 'Residential move'), ('business_move', 'Business move'), ('furniture_transport', 'Furniture transport'), ('furniture_assembly', 'Furniture assembly / disassembly'), ('household_clearance', 'Household clearance'), ('carrying_assistance', 'Carrying assistance'), ('handyman', 'Small job / handyman'), ('not_sure', 'Not sure yet')], max_length=50)),
                ('pickup_address', models.CharField(blank=True, max_length=255)),
                ('pickup_city', models.CharField(blank=True, max_length=100)),
                ('pickup_postal_code', models.CharField(blank=True, max_length=20)),
                ('pickup_floor', models.CharField(blank=True, max_length=30)),
                ('pickup_elevator', models.BooleanField(default=False)),
                ('destination_address', models.CharField(blank=True, max_length=255)),
                ('destination_city', models.CharField(blank=True, max_length=100)),
                ('destination_postal_code', models.CharField(blank=True, max_length=20)),
                ('destination_floor', models.CharField(blank=True, max_length=30)),
                ('destination_elevator', models.BooleanField(default=False)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('items', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('consent_accepted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quote sent'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='quote_uploads/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='quotes.quoterequest')),
            ],
        ),
    ]
